/**
 * @license
 * YUI Tests to Jasmine converter [https://github.com/millermedeiros/YUI_to_Jasmine]
 * Author: Miller Medeiros
 * License: WTFPL
 */
var YUI_to_Jasmine = {

    _HEADER_INFO : '/*---\n Generated by http://millermedeiros.github.com/YUI_to_Jasmine/ (v{version})\n Date: {year}/{month}/{day}\n---*/\n\n',

    VERSION : '0.1.3',

    ASSERTIONS : [
        {
            name : 'areSame',
            pattern : /Y.Assert.areSame\(\s*([^,]+)\s*,\s*([^,;]+).*\);/g, 
            replacement : 'expect( $2 ).toBe( $1 );'
        },
        {
            name : 'areEqual',
            pattern : /Y.Assert.areEqual\(\s*([^,]+)\s*,\s*([^,;]+).*\);/g, 
            replacement: 'expect( $2 ).toEqual( $1 );'
        },
        {
            name : 'isTrue',
            pattern : /Y.Assert.isTrue\(\s*([^,;]+).*\);/g, 
            replacement : 'expect( $1 ).toEqual( true );'
        },
        {
            name : 'isUndefined',
            pattern : /Y.Assert.isUndefined\(\s*([^,;]+).*\);/g, 
            replacement : 'expect( $1 ).toBeUndefined();'
        },
        {
            name : 'isDefined',
            pattern : /Y.Assert.isDefined\(\s*([^,;]+).*\);/g, 
            replacement : 'expect( $1 ).toBeDefined();'
        },
        {
            name : 'fail',
            pattern : /Y.Assert.fail\(\s*(?:(?:['"](.*)['"])|(.*))\s*\);/g,
            replacement : 'expect(null).toEqual(\'fail: $1\');'
        }
    ],

    _getHeader : function(){
        var d = new Date();
        return this._HEADER_INFO
            .replace('{version}', this.VERSION)
            .replace('{day}', d.getDate())
            .replace('{month}', d.getMonth() + 1)
            .replace('{year}', d.getFullYear());
    },

    convert : function(input){
        var n = this.ASSERTIONS.length,
            cur,
            out = this._getHeader() + input;
        while(cur = this.ASSERTIONS[--n]){
            out = out.replace(cur.pattern, cur.replacement);
        }
        return out;
    }

};
